### ISSUE TITLE
does not search in my local mailboxes

### ISSUE THREAD

**Issue by gtolias** [chatchavan/alfred-workflows#2]
The folders listed (or found by search) do not include my local mailboxes (tons of them organized in a hierarchy).

**Comment by chatchavan** [comment]
Thanks for reporting this. I just added this function. Could you test and let me know if it works?

**Comment by gtolias** [comment]
Thank you for the fast response. It does not work. Now it does not list any folder at all -- even worse than before. MacOS 14.1.2 (23B92). Alfred 5.5.1

**Comment by gtolias** [comment]
Update: the main folders are still shown - it just takes much longer to show them. A long list of folders is shown too, all are named "Junk" - see the screenshot. 
<img width="1037" alt="image" src="https://github.com/user-attachments/assets/24b31412-9129-4d51-8302-1efccf4a017a" />

**Comment by chatchavan** [comment]
Thanks for this input.

* I added a progress message, so you know that it is still retrieving the list.
* I fixed the bug with listing the "On My Mac" folders.
* The results are cached, so subsequent calls will not take long. The cache duration is defaulted to 60 minutes. You can change it in the environment variable of the workflow. (In Alfred workflow page, look at the top-right for the button "(x)".)

Please try this version out and let me know whether it works for you.

**Comment by gtolias** [comment]
It works now! This is a super useful workflow. Thanks.
